export { default as Hero } from './Hero'
export { default as Contributions } from './Contributions'
export { default as Testimonials } from './Testimonials'
export { default as Creative } from './Creative'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
