export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Work } from './Work'
export { default as Testimonials } from './Testimonials'
export { default as Creative } from './Creative'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
