// Generates tiny inline blur-up placeholders for the Instagram grid.
// Reads every imageUrl in src/data/instagram.ts, downscales its -320.webp
// variant to 24px, and writes the base64 map to src/data/lqip.ts.
// Run `npm run lqip` after adding posts (after `npm run images`).
import sharp from 'sharp'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = new URL('..', import.meta.url)
const instagramTs = await readFile(new URL('src/data/instagram.ts', root), 'utf8')
const urls = [...instagramTs.matchAll(/imageUrl:\s*'([^']+)'/g)].map((m) => m[1])

const entries = {}
for (const url of urls) {
  const base = url.slice(0, url.lastIndexOf('.'))
  const file = path.join(new URL('public', root).pathname, `${base}-320.webp`)
  const buf = await sharp(file).resize(24).webp({ quality: 40 }).toBuffer()
  entries[url] = `data:image/webp;base64,${buf.toString('base64')}`
}

const out = `// Auto-generated by scripts/generate-lqip.mjs — do not edit.
// Regenerate with \`npm run lqip\` after adding Instagram posts.
export const lqip: Record<string, string> = ${JSON.stringify(entries, null, 2)}
`
await writeFile(new URL('src/data/lqip.ts', root), out)
console.log(`Wrote ${urls.length} LQIP entries to src/data/lqip.ts`)
