// Manifest of source images that should be emitted as responsive variants.
// Sources live in assets-source/ (tracked in git, never shipped by Vite).
// Variants are written into outDir — the public/ path the app actually
// references via srcSet — as `{basename}-{width}.{format}`.
// Add new entries here and rerun `npm run images`.

// Widths beyond the source image's intrinsic width are skipped and warned
// about, rather than clamped into a file whose name overstates its width — the
// srcSet advertises that name, so a clamped variant makes the browser pick a
// candidate believing it has pixels it doesn't. Source dimensions:
//   background.jpg — 2048 x 1365
//   EJS01845.jpg   — 2048 x 1365
//   subject.png    — 1023 x 1066
//
// posts/ — camera exports, all larger than 960px on the short edge
//
// `quality` is optional and merges over the script's defaults
// ({ avif: 55, webp: 78, jpg: 80, png: 90 }). Only override it where the image
// is doing a job that doesn't need the default fidelity.

import { readdirSync } from 'node:fs'

/**
 * Note screenshots do NOT live under public/notes.
 *
 * `/notes/:slug` is rewritten to `/notes/:slug.html` in vercel.json, so a
 * request for /notes/insight-rings-960.avif was rewritten to
 * insight-rings-960.avif.html and 404ed. It worked under `vite preview`, which
 * applies no rewrites, and failed under `vercel dev` and would have failed in
 * production. The route owns that prefix; images take their own.
 *
 * Widths must stay in step with NoteFigure in src/lib/NoteFigure.tsx, which is
 * what the srcSet advertises.
 */
const OUT = 'public/note-shots'
const NOTE_WIDTHS = [640, 960, 1280, 1920]
/** The single PNG the <img> falls back to. Mid-ladder, so it suits most slots. */
const NOTE_FALLBACK_WIDTH = 1280

/**
 * Note screenshots, discovered rather than listed.
 *
 * Everything else in this manifest is a photograph somebody chose, so a hand
 * written entry is the right amount of ceremony. Screenshots are generated by
 * `npm run shots` from scripts/notes-shots.config.mjs, and that file is already
 * the place their names are decided; requiring a second entry here would mean
 * every new figure needs two edits and the failure when you forget the second
 * is a note whose images 404 in production but not in dev.
 *
 * PNG, not JPEG, for the fallback. These are UI screenshots: flat fills, hard
 * type edges, and thin one-pixel rules are exactly what JPEG's chroma
 * subsampling smears.
 */
function noteShots() {
  let files = []
  try {
    files = readdirSync('assets-source/notes').filter(f => f.endsWith('.png'))
  } catch {
    return []  // No screenshots captured yet. Not an error.
  }
  return files.sort().flatMap(file => {
    const src = `assets-source/notes/${file}`
    return [
      { src, outDir: OUT, widths: NOTE_WIDTHS, formats: ['avif', 'webp'] },
      // ONE PNG, at one width, as the <img> fallback and nothing else.
      //
      // A full PNG ladder was 487KB of the 641KB a single screenshot cost, to
      // serve a browser that supports neither AVIF nor WebP. WebP has been
      // universal since 2020 and AVIF since 2024; anything without both is not
      // rendering this site anyway. It gets one correctly sized image rather
      // than a choice of four, which is the right trade for a fallback nobody
      // reaches. `quality` is what switches sharp to palette quantisation on
      // PNG at all; without it the encode is lossless and a dashboard
      // screenshot runs to megabytes.
      { src, outDir: OUT, widths: [NOTE_FALLBACK_WIDTH], formats: ['png'], quality: { png: 88 } },
    ]
  })
}

export default [
  {
    src: 'assets-source/hero/background.jpg',
    outDir: 'public/hero',
    widths: [640, 1280, 1920],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    // Full-bleed decorative background for the Contact section: aria-hidden,
    // under a radial gradient at 75% black and a grain overlay, and never
    // looked at directly. The default quality was spending 869K on an AVIF
    // whose detail is covered up — this is the one image on the site where
    // dropping fidelity costs nothing visible.
    //
    // 2560 is absent on purpose: the source is 2048 wide and cannot fill it.
    src: 'assets-source/contact/EJS01845.jpg',
    outDir: 'public/contact',
    widths: [640, 1280, 1920],
    formats: ['avif', 'webp', 'jpg'],
    quality: { avif: 40, webp: 68, jpg: 74 },
  },
  {
    // png here is only the <picture> fallback behind AVIF and WebP, so it is
    // quantised rather than lossless. See the note in generate-responsive-images
    // about `quality` being what enables that at all.
    src: 'assets-source/hero/subject.png',
    outDir: 'public/hero',
    widths: [512, 1024],
    formats: ['avif', 'webp', 'png'],
    quality: { png: 90 },
  },
  {
    src: 'assets-source/posts/AA2_8841.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    src: 'assets-source/posts/EJS01205.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    src: 'assets-source/posts/EJS01692.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    src: 'assets-source/posts/EJS06506.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    src: 'assets-source/posts/EJS08482.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  {
    src: 'assets-source/posts/EJS08874.jpg',
    outDir: 'public/posts',
    widths: [320, 640, 960],
    formats: ['avif', 'webp', 'jpg'],
  },
  ...noteShots(),
]
